### ISSUE TITLE
Implement Chrome browser notifications when high score is beat

### ISSUE THREAD

**Issue by Sageth** [Sageth/phparcade#9]
If player A has the high score and player B beats the score, Player A should get a browser notification that their score was beaten.

**Comment by MisterBrownRSA** [comment]
@Sageth Wouldn't this need to be done using sockets ? I'm curious, because otherwise you'd have to poll with AJAX...

**Comment by Sageth** [comment]
I haven't looked too deeply into it, other than cursory looks:
https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API 
https://developers.google.com/web/fundamentals/push-notifications/display-a-notification

At a glance, this looks like it's an API call, but like I said, I haven't looked too deeply into it, so it may be much more involved than I initially thought.

**Comment by MisterBrownRSA** [comment]
@Sageth Yes, this is only the type of notification that can be sent.

Typically when handling notifications it's either caller event based, eg. clicked on this button, show a notification.
or
It's socket event based where the back-end software will broadcast an event through something like pusher which the front end will be listening for - which then pushes the notification.

So what you're actually looking for here, is whether or not you're willing to have the user refresh the page in order to get the notification, or will the notification be pushed "real time". I'll run through the code and see if you aren't already using some sort of socket that I can just connect to.

**Comment by Sageth** [comment]
Thanks for the clarification.  I had envisioned the event occurring during score submit process, which should only occur with those types of games.  The score submission should occur here: https://github.com/Sageth/phparcade/blob/master/includes/classes/Scores.php#L53

This is an old codebase (PHP4, or possibly earlier) that I've spent a lot of time modernizing as part of my own learning, so I know the socket_ functions aren't used anywhere.  I do appreciate the insight on this, though.

**Comment by Sageth** [comment]
I've since decided to use Discord for notifications due to the feature set.  This was implemented in fb44d4663425c458778923a063f3666edb568a1e and have had a number of bug fixes to address some specific scenarios since implementation.  Closing issue.
